//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebshopClient.DeliveryDescriptionServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDeliveryDescription", Namespace="http://schemas.datacontract.org/2004/07/Service.Model")]
    [System.SerializableAttribute()]
    public partial class ServiceDeliveryDescription : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DeliveryIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ZipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DeliveryId {
            get {
                return this.DeliveryIdField;
            }
            set {
                if ((this.DeliveryIdField.Equals(value) != true)) {
                    this.DeliveryIdField = value;
                    this.RaisePropertyChanged("DeliveryId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNo {
            get {
                return this.PhoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNoField, value) != true)) {
                    this.PhoneNoField = value;
                    this.RaisePropertyChanged("PhoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ZipCode {
            get {
                return this.ZipCodeField;
            }
            set {
                if ((this.ZipCodeField.Equals(value) != true)) {
                    this.ZipCodeField = value;
                    this.RaisePropertyChanged("ZipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryDescriptionServiceReference.IDeliveryDescriptionService")]
    public interface IDeliveryDescriptionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/InsertDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/InsertDeliveryDescriptionResponse")]
        void InsertDeliveryDescription(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/InsertDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/InsertDeliveryDescriptionResponse")]
        System.Threading.Tasks.Task InsertDeliveryDescriptionAsync(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/GetDeliveryDescriptionById", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/GetDeliveryDescriptionByIdResponse" +
            "")]
        WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription GetDeliveryDescriptionById(int deliveryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/GetDeliveryDescriptionById", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/GetDeliveryDescriptionByIdResponse" +
            "")]
        System.Threading.Tasks.Task<WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription> GetDeliveryDescriptionByIdAsync(int deliveryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/UpdateDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/UpdateDeliveryDescriptionResponse")]
        void UpdateDeliveryDescription(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/UpdateDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/UpdateDeliveryDescriptionResponse")]
        System.Threading.Tasks.Task UpdateDeliveryDescriptionAsync(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/DeleteDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/DeleteDeliveryDescriptionResponse")]
        void DeleteDeliveryDescription(int deliveryId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDeliveryDescriptionService/DeleteDeliveryDescription", ReplyAction="http://tempuri.org/IDeliveryDescriptionService/DeleteDeliveryDescriptionResponse")]
        System.Threading.Tasks.Task DeleteDeliveryDescriptionAsync(int deliveryId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryDescriptionServiceChannel : WebshopClient.DeliveryDescriptionServiceReference.IDeliveryDescriptionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryDescriptionServiceClient : System.ServiceModel.ClientBase<WebshopClient.DeliveryDescriptionServiceReference.IDeliveryDescriptionService>, WebshopClient.DeliveryDescriptionServiceReference.IDeliveryDescriptionService {
        
        public DeliveryDescriptionServiceClient() {
        }
        
        public DeliveryDescriptionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryDescriptionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryDescriptionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryDescriptionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void InsertDeliveryDescription(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription) {
            base.Channel.InsertDeliveryDescription(deliveryDescription);
        }
        
        public System.Threading.Tasks.Task InsertDeliveryDescriptionAsync(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription) {
            return base.Channel.InsertDeliveryDescriptionAsync(deliveryDescription);
        }
        
        public WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription GetDeliveryDescriptionById(int deliveryId) {
            return base.Channel.GetDeliveryDescriptionById(deliveryId);
        }
        
        public System.Threading.Tasks.Task<WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription> GetDeliveryDescriptionByIdAsync(int deliveryId) {
            return base.Channel.GetDeliveryDescriptionByIdAsync(deliveryId);
        }
        
        public void UpdateDeliveryDescription(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription) {
            base.Channel.UpdateDeliveryDescription(deliveryDescription);
        }
        
        public System.Threading.Tasks.Task UpdateDeliveryDescriptionAsync(WebshopClient.DeliveryDescriptionServiceReference.ServiceDeliveryDescription deliveryDescription) {
            return base.Channel.UpdateDeliveryDescriptionAsync(deliveryDescription);
        }
        
        public void DeleteDeliveryDescription(int deliveryId) {
            base.Channel.DeleteDeliveryDescription(deliveryId);
        }
        
        public System.Threading.Tasks.Task DeleteDeliveryDescriptionAsync(int deliveryId) {
            return base.Channel.DeleteDeliveryDescriptionAsync(deliveryId);
        }
    }
}
